### PR TITLE
4447 Add Find Calibration Guards and Tests

### LINKED ISSUE #4447: EUROTHERM: crash when no calibration file read
find_calibration_range_impl() does not check it has read lines from a file before using the vector, so if no file was read this results in a crash when lines[0] is referenced

To reproduce:
* Rename `C:\Instrument\Apps\EPICS-DEBUG2\support\ReadASCII\master\example_settings\Default.txt`
* Start the IOC e.g. `%PYTHON3% run_tests.py -t eurotherm -a`
* Confirm IOC crashes

### PR DESCRIPTION
**Pull request by Scott-James-Hurley**
Closes: ISISComputingGroup/IBEX#4447

This adds guards for accessing data from a file. The related issue states that if the file is not found it will cause a crash when running the Python tests. I was only able to cause this crash by starting the tests and changing the file path while the tests are running. As a result I think the calibration file not being found is handled elsewhere when running these tests. Nonetheless, these guards will be useful if this function is used along some other path.

This also adds tests for `find_calibration_range_impl`, which currently is lacking tests. These tests cover all the different ways I though the calibration file could be wrong.

### CODE REVIEW

File: utilitiesApp/tests/calibration_range_tests.cc [hunk 1]
```diff
@@ -5,12 +5,267 @@
...
+        std::FILE* pFile;
+        pFile = fopen("calibration_range.txt", "w");
+
+        if (pFile != NULL) {
+            std::fputs(data.c_str(), pFile);
+            std::fclose(pFile);
+        }
+    }
+
+    TEST(FindCalibrationRangeTest, reads_in_calibration_range) {
```
Comment (NikolaRoev) [inline utilitiesApp/tests/calibration_range_tests.cc]: Please follow the `GIVEN`, `WHEN`, `THEN` naming convention for your tests.
For examples you can check the existing tests in this file or any of the tests in the IOC Test Framework, [link](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/blob/14f3d62166e3774b8cbd00bf9df98af0678085b3/tests/eurotherm.py#L139).

File: utilitiesApp/tests/calibration_range_tests.cc [hunk 2]
```diff
@@ -5,12 +5,267 @@
...
+        // When:
+        long status = find_calibration_range_impl(&prec);
+
+        // Then:
+        ASSERT_EQ(status, 0);
+        ASSERT_EQ((static_cast<double*>(prec.vala))[0], 10000);
+        ASSERT_EQ((static_cast<double*>(prec.valb))[0], 0);
+
+        // Clean up
+        std::remove(std::string{"calibration_range.txt"}.c_str());
```
Comment (NikolaRoev) [inline utilitiesApp/tests/calibration_range_tests.cc]: No need to create a `std::string` and cast it to a c-string. I would advise just defining a macro or a `const` value of your file name and using that instead of having to pass a literal each time.

File: utilitiesApp/tests/calibration_range_tests.cc [hunk 3]
```diff
@@ -5,12 +5,267 @@
...
+
+        if (pFile != NULL) {
+            std::fputs(data.c_str(), pFile);
+            std::fclose(pFile);
+        }
+    }
+
+    TEST(FindCalibrationRangeTest, reads_in_calibration_range) {
+        // Given
+        aSubRecord prec;
```
Comment (NikolaRoev) [inline utilitiesApp/tests/calibration_range_tests.cc]: You have a lot of repeating code when you are creating the Record and deleting the text file. Have you considered using GTest's `SetUp` and `TearDown` functions?

**Review by NikolaRoev — APPROVED** [review]

**Comment by Tom-Willemsen** [comment]
Merged on behalf of @NikolaRoev as he didn't look to have permissions to merge on this repo
